project:
  type: website

execute: 
  echo: true
  warning: false
  
website:
  title: "GrandNewBlog"
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    backgroundcolor: "#FCEFD3"
    mainfont: Roboto Condensed
    monofont: Fira Code
    code-block-border-left: "black"
    code-block-bg: "#E7FBFE"
    code-link: TRUE
    df-print: paged
    fig-align: center
    fig-cap-location: bottom
    fig-asp: 0.618
    fig-dpi: 300

editor: visual

