{
  "hash": "791d6b6b605b413d5d2d320ffe6ccdc2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Grades in Art, Design, and Vocational Degree\"\norder: 30\n---\n\n\n\n## Intro\n\nAnalyzing the Degree dataset\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(message = FALSE)\nlibrary(tidyverse)\nlibrary(mosaic)\nlibrary(skimr)\nlibrary(crosstable)\nlibrary(ggformula)\nlibrary(supernova)\n```\n:::\n\n\n\n## Read Data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDegree <- readxl::read_xlsx(\"../../data/Art, Design, and Vocation are all diff-different.xlsx\")\nDegree\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"SN\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Degree\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Course\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Letter Grade\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Score\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Gender\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"1\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"2\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"2\",\"5\":\"O\",\"6\":\"9.6\",\"7\":\"F\"},{\"1\":\"3\",\"2\":\"B.Des\",\"3\":\"IADP\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.2\",\"7\":\"F\"},{\"1\":\"4\",\"2\":\"B.Des\",\"3\":\"CE\",\"4\":\"2\",\"5\":\"O\",\"6\":\"9.8\",\"7\":\"F\"},{\"1\":\"5\",\"2\":\"B.Des\",\"3\":\"BSSD\",\"4\":\"2\",\"5\":\"P\",\"6\":\"3.0\",\"7\":\"M\"},{\"1\":\"6\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"2\",\"5\":\"O\",\"6\":\"9.5\",\"7\":\"F\"},{\"1\":\"7\",\"2\":\"B.Des\",\"3\":\"PSD\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"8\",\"2\":\"B.Des\",\"3\":\"PSD\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"9\",\"2\":\"B.Des\",\"3\":\"PSD\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"10\",\"2\":\"B.Des\",\"3\":\"BSSD\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"11\",\"2\":\"B.Des\",\"3\":\"VCSB\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"12\",\"2\":\"B.Des\",\"3\":\"VCSB\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"13\",\"2\":\"B.Des\",\"3\":\"IAIDP\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"14\",\"2\":\"B.Des\",\"3\":\"IAIDP\",\"4\":\"3\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"M\"},{\"1\":\"15\",\"2\":\"B.Des\",\"3\":\"VCSB\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"16\",\"2\":\"B.Des\",\"3\":\"HCD\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"M\"},{\"1\":\"17\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.1\",\"7\":\"F\"},{\"1\":\"18\",\"2\":\"B.Des\",\"3\":\"VCSB\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"19\",\"2\":\"B.Des\",\"3\":\"CE\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"20\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"M\"},{\"1\":\"21\",\"2\":\"B.Des\",\"3\":\"IADP\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"22\",\"2\":\"B.Des\",\"3\":\"IADP\",\"4\":\"3\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"M\"},{\"1\":\"23\",\"2\":\"B.Des\",\"3\":\"VCSB\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"24\",\"2\":\"B.Des\",\"3\":\"CE\",\"4\":\"2\",\"5\":\"O\",\"6\":\"10.0\",\"7\":\"F\"},{\"1\":\"25\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"26\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"27\",\"2\":\"B.Des\",\"3\":\"PSD\",\"4\":\"3\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"28\",\"2\":\"B.Des\",\"3\":\"PSD\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"29\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"30\",\"2\":\"B.Des\",\"3\":\"HCD\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"31\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"3\",\"5\":\"O\",\"6\":\"9.5\",\"7\":\"F\"},{\"1\":\"32\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"33\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"M\"},{\"1\":\"34\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"3\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"M\"},{\"1\":\"35\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"36\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"37\",\"2\":\"B.Voc\",\"3\":\"ID\",\"4\":\"3\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"M\"},{\"1\":\"38\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"O\",\"6\":\"9.5\",\"7\":\"M\"},{\"1\":\"39\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"B\",\"6\":\"6.5\",\"7\":\"M\"},{\"1\":\"40\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"O\",\"6\":\"9.5\",\"7\":\"M\"},{\"1\":\"41\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"O\",\"6\":\"9.5\",\"7\":\"M\"},{\"1\":\"42\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"M\"},{\"1\":\"43\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"O\",\"6\":\"9.5\",\"7\":\"F\"},{\"1\":\"44\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"O\",\"6\":\"9.5\",\"7\":\"F\"},{\"1\":\"45\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"B\",\"6\":\"6.5\",\"7\":\"F\"},{\"1\":\"46\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"C\",\"6\":\"5.0\",\"7\":\"M\"},{\"1\":\"47\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"1\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"M\"},{\"1\":\"48\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"1\",\"5\":\"B\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"49\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"1\",\"5\":\"B\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"50\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"1\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"51\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"1\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"52\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"1\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"53\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"54\",\"2\":\"B.Voc\",\"3\":\"GADP\",\"4\":\"1\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"55\",\"2\":\"B.Voc\",\"3\":\"GADP\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"56\",\"2\":\"B.Voc\",\"3\":\"Film\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"57\",\"2\":\"B.Voc\",\"3\":\"GADP\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"58\",\"2\":\"B.Voc\",\"3\":\"GADP\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"59\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"60\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"61\",\"2\":\"B.FA\",\"3\":\"CAP\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"62\",\"2\":\"B.FA\",\"3\":\"CAP\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"M\"},{\"1\":\"63\",\"2\":\"B.FA\",\"3\":\"CAP\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"64\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"8.5\",\"7\":\"M\"},{\"1\":\"65\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"66\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"67\",\"2\":\"B.FA\",\"3\":\"CAP\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"68\",\"2\":\"B.FA\",\"3\":\"CAP\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"69\",\"2\":\"B.FA\",\"3\":\"Film\",\"4\":\"3\",\"5\":\"B\",\"6\":\"6.0\",\"7\":\"M\"},{\"1\":\"70\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"71\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"72\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"73\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"74\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"75\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B\",\"6\":\"6.0\",\"7\":\"M\"},{\"1\":\"76\",\"2\":\"B.FA\",\"3\":\"Film\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"77\",\"2\":\"B.FA\",\"3\":\"Film\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"78\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"79\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"80\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"81\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"82\",\"2\":\"B.FA\",\"3\":\"Film\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"83\",\"2\":\"B.FA\",\"3\":\"Film\",\"4\":\"3\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"84\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"85\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"86\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"87\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"88\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"M\"},{\"1\":\"89\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"90\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n## Munging\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDegree_modified <- Degree %>%\n  mutate(Gender = as_factor(Gender),\n         Degree = as_factor(Degree))\nDegree_modified\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"SN\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Degree\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Course\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Letter Grade\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Score\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Gender\"],\"name\":[7],\"type\":[\"fct\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"1\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"2\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"2\",\"5\":\"O\",\"6\":\"9.6\",\"7\":\"F\"},{\"1\":\"3\",\"2\":\"B.Des\",\"3\":\"IADP\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.2\",\"7\":\"F\"},{\"1\":\"4\",\"2\":\"B.Des\",\"3\":\"CE\",\"4\":\"2\",\"5\":\"O\",\"6\":\"9.8\",\"7\":\"F\"},{\"1\":\"5\",\"2\":\"B.Des\",\"3\":\"BSSD\",\"4\":\"2\",\"5\":\"P\",\"6\":\"3.0\",\"7\":\"M\"},{\"1\":\"6\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"2\",\"5\":\"O\",\"6\":\"9.5\",\"7\":\"F\"},{\"1\":\"7\",\"2\":\"B.Des\",\"3\":\"PSD\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"8\",\"2\":\"B.Des\",\"3\":\"PSD\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"9\",\"2\":\"B.Des\",\"3\":\"PSD\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"10\",\"2\":\"B.Des\",\"3\":\"BSSD\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"11\",\"2\":\"B.Des\",\"3\":\"VCSB\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"12\",\"2\":\"B.Des\",\"3\":\"VCSB\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"13\",\"2\":\"B.Des\",\"3\":\"IAIDP\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"14\",\"2\":\"B.Des\",\"3\":\"IAIDP\",\"4\":\"3\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"M\"},{\"1\":\"15\",\"2\":\"B.Des\",\"3\":\"VCSB\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"16\",\"2\":\"B.Des\",\"3\":\"HCD\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"M\"},{\"1\":\"17\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.1\",\"7\":\"F\"},{\"1\":\"18\",\"2\":\"B.Des\",\"3\":\"VCSB\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"19\",\"2\":\"B.Des\",\"3\":\"CE\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"20\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"M\"},{\"1\":\"21\",\"2\":\"B.Des\",\"3\":\"IADP\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"22\",\"2\":\"B.Des\",\"3\":\"IADP\",\"4\":\"3\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"M\"},{\"1\":\"23\",\"2\":\"B.Des\",\"3\":\"VCSB\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"24\",\"2\":\"B.Des\",\"3\":\"CE\",\"4\":\"2\",\"5\":\"O\",\"6\":\"10.0\",\"7\":\"F\"},{\"1\":\"25\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"26\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"27\",\"2\":\"B.Des\",\"3\":\"PSD\",\"4\":\"3\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"28\",\"2\":\"B.Des\",\"3\":\"PSD\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"29\",\"2\":\"B.Des\",\"3\":\"CAC\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"30\",\"2\":\"B.Des\",\"3\":\"HCD\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"31\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"3\",\"5\":\"O\",\"6\":\"9.5\",\"7\":\"F\"},{\"1\":\"32\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"33\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"M\"},{\"1\":\"34\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"3\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"M\"},{\"1\":\"35\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"36\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"37\",\"2\":\"B.Voc\",\"3\":\"ID\",\"4\":\"3\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"M\"},{\"1\":\"38\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"O\",\"6\":\"9.5\",\"7\":\"M\"},{\"1\":\"39\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"B\",\"6\":\"6.5\",\"7\":\"M\"},{\"1\":\"40\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"O\",\"6\":\"9.5\",\"7\":\"M\"},{\"1\":\"41\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"O\",\"6\":\"9.5\",\"7\":\"M\"},{\"1\":\"42\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"M\"},{\"1\":\"43\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"O\",\"6\":\"9.5\",\"7\":\"F\"},{\"1\":\"44\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"O\",\"6\":\"9.5\",\"7\":\"F\"},{\"1\":\"45\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"B\",\"6\":\"6.5\",\"7\":\"F\"},{\"1\":\"46\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"3\",\"5\":\"C\",\"6\":\"5.0\",\"7\":\"M\"},{\"1\":\"47\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"1\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"M\"},{\"1\":\"48\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"1\",\"5\":\"B\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"49\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"1\",\"5\":\"B\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"50\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"1\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"51\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"1\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"52\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"1\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"53\",\"2\":\"B.Voc\",\"3\":\"UIID\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"54\",\"2\":\"B.Voc\",\"3\":\"GADP\",\"4\":\"1\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"55\",\"2\":\"B.Voc\",\"3\":\"GADP\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"56\",\"2\":\"B.Voc\",\"3\":\"Film\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"57\",\"2\":\"B.Voc\",\"3\":\"GADP\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"58\",\"2\":\"B.Voc\",\"3\":\"GADP\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"59\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"60\",\"2\":\"B.Voc\",\"3\":\"DMP\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"61\",\"2\":\"B.FA\",\"3\":\"CAP\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"62\",\"2\":\"B.FA\",\"3\":\"CAP\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"M\"},{\"1\":\"63\",\"2\":\"B.FA\",\"3\":\"CAP\",\"4\":\"3\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"64\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"8.5\",\"7\":\"M\"},{\"1\":\"65\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"66\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"67\",\"2\":\"B.FA\",\"3\":\"CAP\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"68\",\"2\":\"B.FA\",\"3\":\"CAP\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"69\",\"2\":\"B.FA\",\"3\":\"Film\",\"4\":\"3\",\"5\":\"B\",\"6\":\"6.0\",\"7\":\"M\"},{\"1\":\"70\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"71\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"72\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"73\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"74\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"75\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B\",\"6\":\"6.0\",\"7\":\"M\"},{\"1\":\"76\",\"2\":\"B.FA\",\"3\":\"Film\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"77\",\"2\":\"B.FA\",\"3\":\"Film\",\"4\":\"3\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"78\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"79\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"80\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"81\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"82\",\"2\":\"B.FA\",\"3\":\"Film\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"F\"},{\"1\":\"83\",\"2\":\"B.FA\",\"3\":\"Film\",\"4\":\"3\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"84\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A+\",\"6\":\"9.0\",\"7\":\"F\"},{\"1\":\"85\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"A\",\"6\":\"8.0\",\"7\":\"M\"},{\"1\":\"86\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"87\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"88\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"M\"},{\"1\":\"89\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"},{\"1\":\"90\",\"2\":\"B.FA\",\"3\":\"DMA\",\"4\":\"2\",\"5\":\"B+\",\"6\":\"7.0\",\"7\":\"F\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nDegree_modified %>% \n  crosstable(Score ~ Degree) %>% \n  as_flextable()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-f864ab70{table-layout:auto;}.cl-f84be950{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-f84be96e{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-f84d70e0{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-f84d711c{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-f84d8634{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f84d863e{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f84d863f{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f84d8640{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f84d8648{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-f864ab70'><thead><tr style=\"overflow-wrap:break-word;\"><th  rowspan=\"2\"class=\"cl-f84d8634\"><p class=\"cl-f84d70e0\"><span class=\"cl-f84be950\">label</span></p></th><th  rowspan=\"2\"class=\"cl-f84d8634\"><p class=\"cl-f84d70e0\"><span class=\"cl-f84be950\">variable</span></p></th><th  colspan=\"3\"class=\"cl-f84d863e\"><p class=\"cl-f84d70e0\"><span class=\"cl-f84be950\">Degree</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-f84d863f\"><p class=\"cl-f84d70e0\"><span class=\"cl-f84be950\">B.Des</span></p></th><th class=\"cl-f84d863f\"><p class=\"cl-f84d70e0\"><span class=\"cl-f84be950\">B.Voc</span></p></th><th class=\"cl-f84d863f\"><p class=\"cl-f84d70e0\"><span class=\"cl-f84be950\">B.FA</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td  rowspan=\"4\"class=\"cl-f84d8640\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">Score</span></p></td><td class=\"cl-f84d8648\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">Min / Max</span></p></td><td class=\"cl-f84d8648\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">3.0 / 10.0</span></p></td><td class=\"cl-f84d8648\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">5.0 / 9.5</span></p></td><td class=\"cl-f84d8648\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">6.0 / 9.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-f84d8648\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">Med [IQR]</span></p></td><td class=\"cl-f84d8648\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">9.0 [8.0;9.0]</span></p></td><td class=\"cl-f84d8648\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">8.0 [8.0;9.0]</span></p></td><td class=\"cl-f84d8648\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">8.0 [7.0;8.0]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-f84d8648\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">Mean (std)</span></p></td><td class=\"cl-f84d8648\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">8.4 (1.3)</span></p></td><td class=\"cl-f84d8648\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">8.2 (1.1)</span></p></td><td class=\"cl-f84d8648\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">7.6 (0.8)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-f84d8640\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">N (NA)</span></p></td><td class=\"cl-f84d8640\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">30 (0)</span></p></td><td class=\"cl-f84d8640\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">30 (0)</span></p></td><td class=\"cl-f84d8640\"><p class=\"cl-f84d711c\"><span class=\"cl-f84be96e\">30 (0)</span></p></td></tr></tbody></table></div>\n```\n\n:::\n\n```{.r .cell-code}\n##\nDegree_modified %>% \n  crosstable(Score ~ Degree + Gender) %>% \n  as_flextable()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-f87f4a34{table-layout:auto;}.cl-f87b3868{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-f87b3872{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-f87cd97a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-f87cd97b{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-f87ceb0e{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f87ceb18{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f87ceb19{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f87ceb22{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 1pt solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f87ceb23{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f87ceb24{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f87ceb2c{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 1pt solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f87ceb2d{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f87ceb36{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f87ceb40{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f87ceb41{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f87ceb42{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f87ceb4a{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-f87f4a34'><thead><tr style=\"overflow-wrap:break-word;\"><th  colspan=\"2\"class=\"cl-f87ceb0e\"><p class=\"cl-f87cd97a\"><span class=\"cl-f87b3868\">Gender</span></p></th><th  colspan=\"3\"class=\"cl-f87ceb0e\"><p class=\"cl-f87cd97a\"><span class=\"cl-f87b3868\">F</span></p></th><th  colspan=\"3\"class=\"cl-f87ceb19\"><p class=\"cl-f87cd97a\"><span class=\"cl-f87b3868\">M</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th  colspan=\"2\"class=\"cl-f87ceb23\"><p class=\"cl-f87cd97a\"><span class=\"cl-f87b3868\">Degree</span></p></th><th class=\"cl-f87ceb23\"><p class=\"cl-f87cd97a\"><span class=\"cl-f87b3868\">B.Des</span></p></th><th class=\"cl-f87ceb24\"><p class=\"cl-f87cd97a\"><span class=\"cl-f87b3868\">B.Voc</span></p></th><th class=\"cl-f87ceb24\"><p class=\"cl-f87cd97a\"><span class=\"cl-f87b3868\">B.FA</span></p></th><th class=\"cl-f87ceb23\"><p class=\"cl-f87cd97a\"><span class=\"cl-f87b3868\">B.Des</span></p></th><th class=\"cl-f87ceb24\"><p class=\"cl-f87cd97a\"><span class=\"cl-f87b3868\">B.Voc</span></p></th><th class=\"cl-f87ceb2c\"><p class=\"cl-f87cd97a\"><span class=\"cl-f87b3868\">B.FA</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td  rowspan=\"4\"class=\"cl-f87ceb2d\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">Score</span></p></td><td class=\"cl-f87ceb36\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">Min / Max</span></p></td><td class=\"cl-f87ceb40\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">7.0 / 10.0</span></p></td><td class=\"cl-f87ceb36\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">6.5 / 9.5</span></p></td><td class=\"cl-f87ceb36\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">7.0 / 9.0</span></p></td><td class=\"cl-f87ceb40\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">3.0 / 9.0</span></p></td><td class=\"cl-f87ceb36\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">5.0 / 9.5</span></p></td><td class=\"cl-f87ceb41\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">6.0 / 9.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-f87ceb36\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">Med [IQR]</span></p></td><td class=\"cl-f87ceb40\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">9.0 [8.0;9.1]</span></p></td><td class=\"cl-f87ceb36\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">8.0 [8.0;9.0]</span></p></td><td class=\"cl-f87ceb36\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">7.0 [7.0;8.0]</span></p></td><td class=\"cl-f87ceb40\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">8.0 [7.0;8.5]</span></p></td><td class=\"cl-f87ceb36\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">8.0 [7.5;9.0]</span></p></td><td class=\"cl-f87ceb41\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">8.0 [7.5;8.0]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-f87ceb36\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">Mean (std)</span></p></td><td class=\"cl-f87ceb40\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">8.7 (0.8)</span></p></td><td class=\"cl-f87ceb36\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">8.3 (1.0)</span></p></td><td class=\"cl-f87ceb36\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">7.6 (0.7)</span></p></td><td class=\"cl-f87ceb40\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">7.3 (2.1)</span></p></td><td class=\"cl-f87ceb36\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">8.1 (1.3)</span></p></td><td class=\"cl-f87ceb41\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">7.7 (1.0)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-f87ceb42\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">N (NA)</span></p></td><td class=\"cl-f87ceb2d\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">23 (0)</span></p></td><td class=\"cl-f87ceb42\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">15 (0)</span></p></td><td class=\"cl-f87ceb42\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">19 (0)</span></p></td><td class=\"cl-f87ceb2d\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">7 (0)</span></p></td><td class=\"cl-f87ceb42\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">15 (0)</span></p></td><td class=\"cl-f87ceb4a\"><p class=\"cl-f87cd97b\"><span class=\"cl-f87b3872\">11 (0)</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nDegree_modified %>% \n  gf_density(~ Score | Degree,\n             colour = ~ Degree, fill = ~ Degree, alpha = 0.3) %>% \n  gf_fitdistr(dist = \"norm\") %>% \n  gf_refine(theme_classic())\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=2100}\n:::\n\n```{.r .cell-code}\nDegree_modified %>% \n  group_by(Degree) %>% \n  summarize (mean_Score = mean(Score))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Degree\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"mean_Score\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"B.Des\",\"2\":\"8.373333\"},{\"1\":\"B.Voc\",\"2\":\"8.200000\"},{\"1\":\"B.FA\",\"2\":\"7.616667\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\nNot really Gaussian? Some look ok!!\n\n## Shapiro Test\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(Degree_modified %>% \n               filter(Degree == \"B.Des\") %>% \n               select(Score) %>%  \n               as_vector()) # Can't handle even single col data frame\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  Degree_modified %>% filter(Degree == \"B.Des\") %>% select(Score) %>% as_vector()\nW = 0.75265, p-value = 1.005e-05\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(Degree_modified %>% \n               filter(Degree == \"B.Voc\") %>% \n               select(Score) %>%  \n               as_vector()) # Can't handle even single col data frame\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  Degree_modified %>% filter(Degree == \"B.Voc\") %>% select(Score) %>% as_vector()\nW = 0.88734, p-value = 0.004176\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(Degree_modified %>% \n               filter(Degree == \"B.FA\") %>% \n               select(Score) %>%  \n               as_vector()) # Can't handle even single col data frame\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  Degree_modified %>% filter(Degree == \"B.FA\") %>% select(Score) %>% as_vector()\nW = 0.87451, p-value = 0.002115\n```\n\n\n:::\n:::\n\n\n\nNothing in SMI is normal, folks.\n\n## Inference\n\n### ANOVA\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Set Theme\ntheme_set(theme_classic())\n##\nanova_model <- aov(Score ~ Degree, data = Degree_modified) \n\nanova_model %>% \n  supernova::supernova()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Analysis of Variance Table (Type III SS)\n Model: Score ~ Degree\n\n                              SS df    MS     F   PRE     p\n ----- --------------- | ------- -- ----- ----- ----- -----\n Model (error reduced) |   9.429  2 4.714 3.900 .0823 .0239\n Error (from model)    | 105.160 87 1.209                  \n ----- --------------- | ------- -- ----- ----- ----- -----\n Total (empty model)   | 114.589 89 1.288                  \n```\n\n\n:::\n\n```{.r .cell-code}\nsupernova::pairwise(anova_model, correction = \"Tukey\", \n                    alpha = 0.05, \n                    var_equal = FALSE,\n                    plot = TRUE)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=2100}\n:::\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  group_1 group_2   diff pooled_se      q    df  lower  upper p_adj\n  <chr>   <chr>    <dbl>     <dbl>  <dbl> <int>  <dbl>  <dbl> <dbl>\n1 B.Voc   B.Des   -0.173     0.201 -0.864    87 -0.850  0.504 .8147\n2 B.FA    B.Des   -0.757     0.201 -3.770    87 -1.434 -0.080 .0246\n3 B.FA    B.Voc   -0.583     0.201 -2.906    87 -1.260  0.094 .1054\n```\n\n\n:::\n:::\n\n\n\nTrying a couple of more plots:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(anova_model,conf.level = 0.95) %>% broom::tidy()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"term\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"contrast\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"null.value\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"estimate\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"conf.low\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"conf.high\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"adj.p.value\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Degree\",\"2\":\"B.Voc-B.Des\",\"3\":\"0\",\"4\":\"-0.1733333\",\"5\":\"-0.8502175\",\"6\":\"0.50355079\",\"7\":\"0.81472057\"},{\"1\":\"Degree\",\"2\":\"B.FA-B.Des\",\"3\":\"0\",\"4\":\"-0.7566667\",\"5\":\"-1.4335508\",\"6\":\"-0.07978254\",\"7\":\"0.02461292\"},{\"1\":\"Degree\",\"2\":\"B.FA-B.Voc\",\"3\":\"0\",\"4\":\"-0.5833333\",\"5\":\"-1.2602175\",\"6\":\"0.09355079\",\"7\":\"0.10541986\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nTukeyHSD(anova_model) %>% \n  broom::tidy() %>% \n  gf_errorbar(conf.low + conf.high ~ contrast, color = ~ contrast, width = 0.2, linewidth = 1) %>% \n  gf_point(estimate ~ contrast) %>% \n  gf_hline(yintercept = 0, linetype = \"dashed\") %>% \n  gf_theme(theme_classic()) %>% \n  gf_refine(coord_flip())\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=2100}\n:::\n\n```{.r .cell-code}\n###\n\nTukeyHSD(anova_model) %>% \n  ggiraphExtra::ggHSD() %>% \n  gf_theme(theme_classic()) %>% \n  gf_theme(theme(axis.text.y = element_text(size = 8, angle = 0)))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-2.png){width=2100}\n:::\n:::\n\n\nANOVA says the reduction in error Sum of Squares is merely 9.429! The `p.value` is $0.0239$ so there **is** a significant difference in mean academic scores across the three degree awards. The Significance score is a **single star** so this is also not too significant a difference.\n\nThere seems to be a significant difference between B.Des and B.FA. Poor saps who are doing art. Isn't Design always easier to assess?\n\nLet us state the model equation using `supernova`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsupernova::equation(anova_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFitted equation:\nScore = 8.373333 + -0.1733333*DegreeB.Voc + -0.7566667*DegreeB.FA + e\n```\n\n\n:::\n:::\n\n\n\n### Permutation Test\n\nJust for kicks, a permutation test. Here since there are three groups, we will choose the one metric that tells us if there is a difference between them: the F-statistic.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nF_stat <- anova_model %>% \n  supernova::supernova() %>%  pluck(1,6,1) # OK, the F-Statistic\nF_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.900206\n```\n\n\n:::\n\n```{.r .cell-code}\n##\n\n  \nperm_anova_dist <- do(4999) * aov(Score ~ shuffle(Degree), data = Degree_modified) %>% supernova() %>% pluck(1,6,1)  \n\nhead(perm_anova_dist)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"result\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"0.2896662596\",\"_rn_\":\"1\"},{\"1\":\"0.3220040968\",\"_rn_\":\"2\"},{\"1\":\"1.7225143873\",\"_rn_\":\"3\"},{\"1\":\"0.0002530799\",\"_rn_\":\"4\"},{\"1\":\"0.3785816356\",\"_rn_\":\"5\"},{\"1\":\"0.0692003112\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\ngf_histogram(~ result, data = perm_anova_dist) %>% \n  gf_vline(xintercept = ~ F_stat, color = \"red\") %>% \n  gf_theme(theme_classic())\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=2100}\n:::\n\n```{.r .cell-code}\nprop(perm_anova_dist$result >= F_stat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n prop_TRUE \n0.02260452 \n```\n\n\n:::\n:::\n\n\n\nThe computed `p.value` is 0.027, so there is at least one group that is different in academic grades. The TukeyHSD tells us which one, and at what level of significance.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}